### PR TITLE
Fix #114

### LINKED ISSUE #114: Warning in `phenom_d` implementation
Been seeing the following warning that we should address when making calls to `phenom_d`. 

```
phenom_d.py:950: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3637.)
  f_minus_alpha5_fRD = (Mf.T - alpha5 * fRD).T
```

### PR DESCRIPTION
**Pull request by deepchatterjeeligo**
fixes #114

### CODE REVIEW

**Comment by EthanMarx** [comment]
Looks good. Just some pre-commit issues it seems

**Comment by deepchatterjeeligo** [comment]
Interesting that the pre-commit is failing for `docs/conf.py` which I have not touched. Let me try re-running it locally.

**Comment by deepchatterjeeligo** [comment]
The pre-commit step runs fine for me locally.
```
$ pre-commit run --all-files
isort (python)...........................................................Passed
black....................................................................Passed
flake8...................................................................Passed
Fix End of Files.........................................................Passed
poetry-check.............................................................Passed
poetry-lock..............................................................Passed
```
Do you see anything off?

**Comment by EthanMarx** [comment]
Weird, can you try re-installing the pre-commit hooks? `pre-commit install --all`

**Comment by deepchatterjeeligo** [comment]
> Weird, can you try re-installing the pre-commit hooks? `pre-commit install --all`

Same result.

**Comment by mcoughlin** [comment]
@deepchatterjeeligo is your pre-commit up to date? I.e pip install pre-commit --update or whatever?

**Comment by deepchatterjeeligo** [comment]
> pip install pre-commit --update

```
$  pip install pre-commit --upgrade
$ pre-commit install --all
$ pre-commit run --all-files
isort (python)...........................................................Passed
black....................................................................Passed
flake8...................................................................Passed
Fix End of Files.........................................................Passed
poetry-check.............................................................Passed
poetry-lock..............................................................Passed
```
same result :)

**Comment by deepchatterjeeligo** [comment]
Huh, rebasing this after the InMemory dataset MR fixed the pre-commit!

**Comment by EthanMarx** [comment]
Great. Was going to suggest that. Will approve

**Review by EthanMarx — APPROVED** [review]

**Pull request merged**
