### PR TITLE
Torch dependency fix into dev

### PR DESCRIPTION
**Pull request by EthanMarx**

### CODE REVIEW

**Comment by EthanMarx** [comment]
@wbenoit26 the last torch dependency fix PR wen't directly into main on accident. 

Opening up this one to get that fix into dev. Then, can merge `dev` into `main` with #123 to get in some of the latest updates ( qtransform, distribution changes, InMemoryDataset changes)

**Review by wbenoit26 — APPROVED** [review]

**Comment by wbenoit26** [comment]
Or wait, I see that you also removed the `gwpy` dep here. Intentional?

**Comment by EthanMarx** [comment]
Nope good catch - that was introduced in `dev` for testing qtransform right?

**Comment by wbenoit26** [comment]
Yeah exactly

**Pull request merged**
